"use client";

import Link from "next/link";
import { useState } from "react";
import { logoutAction } from "@/app/(auth)/actions";
import type { DashboardData } from "@/app/lib/dashboard";

type Slice = { label: string; value: number };
type Trend = { label: string; value: number };

const money = (value: number) => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(value).replace("PKR", "Rs");
const compactMoney = (value: number) => value >= 1_000_000 ? `Rs ${(value / 1_000_000).toFixed(1)}M` : value >= 1_000 ? `Rs ${(value / 1_000).toFixed(1)}K` : `Rs ${value.toFixed(0)}`;
const statusColor: Record<string, string> = { PENDING: "bg-rose-400/15 text-rose-300", PREPARING: "bg-amber-400/15 text-amber-300", READY: "bg-emerald-400/15 text-emerald-300", COMPLETED: "bg-sky-400/15 text-sky-300" };
const typeLabel = (value: string | null) => value ? value.replace("_", "-").toLowerCase().replace(/^./, (letter) => letter.toUpperCase()) : "Not recorded";

export default function DashboardClient({ data, adminEmail }: { data: DashboardData; adminEmail: string }) {
  return <div className="min-h-screen bg-[#07111f] text-slate-100"><div className="mx-auto flex min-h-screen max-w-[1800px]">
    <Sidebar />
    <main className="min-w-0 flex-1 px-4 py-5 sm:px-6 lg:px-8">
      <Topbar adminEmail={adminEmail} />
      <div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">{new Intl.DateTimeFormat("en-US", { dateStyle: "full", timeZone: "Asia/Karachi" }).format(new Date(data.generatedAt))}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-white">Restaurant overview</h1><p className="mt-1 text-sm text-slate-400">Live sales, orders, catalog and kitchen activity.</p></div><RangeTabs active={data.range} /></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <MetricCard icon="↗" tone="emerald" label="Today's sales" value={money(data.metrics.todayRevenue)} detail="Completed orders today" />
        <MetricCard icon="₨" tone="blue" label={`${data.periodLabel} sales`} value={money(data.metrics.revenue)} detail="Completed revenue" />
        <MetricCard icon="▣" tone="violet" label="Total orders" value={String(data.metrics.orderCount)} detail={`During ${data.periodLabel.toLowerCase()}`} />
        <MetricCard icon="◎" tone="orange" label="Avg. order value" value={money(data.metrics.averageOrder)} detail="Per completed order" />
        <MetricCard icon="≋" tone="cyan" label="Avg. sales / day" value={money(data.metrics.averagePerDay)} detail={data.range === "today" ? "Today" : `Across ${data.range === "week" ? 7 : 30} days`} />
      </div>
      <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(300px,0.85fr)]"><div className="space-y-4">
        <Panel title="Revenue overview" subtitle={`${money(data.metrics.revenue)} in ${data.periodLabel.toLowerCase()}`} action={<RangeTabs active={data.range} compact />}><LineChart data={data.trend} /></Panel>
        <div className="grid gap-4 lg:grid-cols-3"><Panel title="Top selling items"><TopItems items={data.topItems} /></Panel><Panel title="Category sales"><DonutChart data={data.categorySales} total={data.metrics.revenue} /></Panel><Panel title="Payment methods"><DonutChart data={data.paymentSales} total={data.metrics.revenue} /></Panel></div>
        <div className="grid gap-4 lg:grid-cols-[1.15fr_0.85fr]"><Panel title="Peak hours" subtitle="Completed orders by two-hour window"><BarChart data={data.peakHours} /></Panel><Panel title="Inventory alerts" action={<Link href="/admin/menu" className="text-xs font-semibold text-sky-400">Manage menu</Link>}><InventoryList items={data.inventory} /></Panel></div>
        <Panel title="Recent orders" subtitle="Latest activity across every status"><RecentOrders orders={data.recentOrders} /></Panel>
      </div><aside className="space-y-4"><Panel title="Live order queue" action={<Link href="/kitchen" className="text-xs font-semibold text-sky-400">Open kitchen</Link>}><LiveOrders orders={data.liveOrders} /></Panel><Panel title="Business overview"><BusinessHealth data={data} /></Panel><Panel title="Quick actions"><QuickActions /></Panel></aside></div>
    </main>
  </div></div>;
}

function Sidebar() {
  const links = [["⌂", "Dashboard", "/admin/dashboard"], ["▤", "Orders", "/admin/dashboard#recent-orders"], ["♨", "Kitchen", "/kitchen"], ["☷", "Menu", "/admin/menu"], ["◇", "Deals", "/admin/deals"], ["%", "Coupons", "/admin/coupons"]];
  return <aside className="sticky top-0 hidden h-screen w-52 shrink-0 border-r border-white/7 bg-[#091522] p-4 lg:flex lg:flex-col"><div className="flex items-center gap-3 px-2 py-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-linear-to-br from-sky-400 to-blue-600 text-xl font-black">P</div><div><div className="font-bold text-white">POS Control</div><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Restaurant</div></div></div><nav className="mt-6 space-y-1">{links.map(([icon, label, href], index) => <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${index === 0 ? "bg-sky-500/15 text-sky-300" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className="w-5 text-center text-lg">{icon}</span>{label}</Link>)}</nav><div className="mt-auto rounded-xl border border-violet-400/15 bg-violet-400/7 p-4"><p className="text-xs font-semibold text-violet-300">Catalog tools</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Manage products, inventory and combo deals.</p><Link href="/admin/menu" className="mt-3 block rounded-lg bg-violet-500/15 px-3 py-2 text-center text-xs font-semibold text-violet-200">Open catalog</Link></div></aside>;
}

function Topbar({ adminEmail }: { adminEmail: string }) {
  return <header className="flex items-center justify-between gap-4 border-b border-white/7 pb-5"><div className="flex items-center gap-3 lg:hidden"><div className="grid h-9 w-9 place-items-center rounded-lg bg-sky-500 font-bold">P</div><span className="font-bold">POS Control</span></div><div className="ml-auto flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-semibold text-white">{adminEmail.split("@")[0]}</p><p className="text-xs text-slate-500">Administrator</p></div><div className="grid h-10 w-10 place-items-center rounded-full bg-linear-to-br from-sky-400 to-violet-500 font-bold">{adminEmail[0]?.toUpperCase()}</div><form action={logoutAction}><button className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-400 hover:bg-white/5 hover:text-white">Log out</button></form></div></header>;
}

function RangeTabs({ active, compact = false }: { active: DashboardData["range"]; compact?: boolean }) {
  return <div className={`flex rounded-xl border border-white/8 bg-white/3 ${compact ? "p-0.5" : "p-1"}`}>{(["today", "week", "month"] as const).map((range) => <Link key={range} href={`/admin/dashboard?range=${range}`} className={`${compact ? "px-2.5 py-1 text-[10px]" : "px-4 py-2 text-xs"} rounded-lg font-semibold capitalize ${active === range ? "bg-slate-700 text-white shadow" : "text-slate-500 hover:text-slate-200"}`}>{range}</Link>)}</div>;
}

const tones = { emerald: "bg-emerald-400/12 text-emerald-300 ring-emerald-400/20", blue: "bg-blue-400/12 text-blue-300 ring-blue-400/20", violet: "bg-violet-400/12 text-violet-300 ring-violet-400/20", orange: "bg-orange-400/12 text-orange-300 ring-orange-400/20", cyan: "bg-cyan-400/12 text-cyan-300 ring-cyan-400/20" };
function MetricCard({ icon, tone, label, value, detail }: { icon: string; tone: keyof typeof tones; label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-white/7 bg-[#0d1b2a] p-4 shadow-xl shadow-black/5"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-full text-xl ring-1 ${tones[tone]}`}>{icon}</span><div className="min-w-0"><p className="truncate text-xs font-medium text-slate-400">{label}</p><p className="mt-1 truncate text-xl font-bold text-white">{value}</p></div></div><p className="mt-3 text-[11px] text-slate-500">{detail}</p></div>; }
function Panel({ title, subtitle, action, children }: { title: string; subtitle?: string; action?: React.ReactNode; children: React.ReactNode }) { return <section id={title === "Recent orders" ? "recent-orders" : undefined} className="rounded-2xl border border-white/7 bg-[#0d1b2a] p-4 shadow-xl shadow-black/5 sm:p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-white">{title}</h2>{subtitle && <p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div>{action}</div>{children}</section>; }

function LineChart({ data }: { data: Trend[] }) {
  const width = 900, height = 250, padX = 34, padY = 25, max = Math.max(...data.map((item) => item.value), 1);
  const points = data.map((item, index) => ({ x: padX + index * ((width - padX * 2) / Math.max(data.length - 1, 1)), y: height - padY - item.value / max * (height - padY * 2), ...item }));
  const line = points.map((point) => `${point.x},${point.y}`).join(" "), area = `${padX},${height - padY} ${line} ${width - padX},${height - padY}`;
  return <div className="overflow-hidden"><svg viewBox={`0 0 ${width} ${height + 26}`} role="img" aria-label="Revenue trend" className="h-72 w-full"><defs><linearGradient id="revenueArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#22c55e" stopOpacity=".32"/><stop offset="1" stopColor="#22c55e" stopOpacity="0"/></linearGradient></defs>{[0, .25, .5, .75, 1].map((ratio) => <g key={ratio}><line x1={padX} x2={width - padX} y1={padY + ratio * (height - padY * 2)} y2={padY + ratio * (height - padY * 2)} stroke="#263446" strokeDasharray="4 5"/><text x="0" y={padY + ratio * (height - padY * 2) + 4} fill="#64748b" fontSize="10">{compactMoney(max * (1 - ratio)).replace("Rs ", "")}</text></g>)}<polygon points={area} fill="url(#revenueArea)"/><polyline points={line} fill="none" stroke="#22c55e" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{points.map((point, index) => <g key={`${point.label}-${index}`}><circle cx={point.x} cy={point.y} r="4" fill="#07111f" stroke="#34d399" strokeWidth="3"><title>{`${point.label}: ${money(point.value)}`}</title></circle>{(data.length <= 12 || index % 3 === 0 || index === data.length - 1) && <text x={point.x} y={height + 12} textAnchor="middle" fill="#64748b" fontSize="9">{point.label}</text>}</g>)}</svg></div>;
}

function TopItems({ items }: { items: DashboardData["topItems"] }) { const max = Math.max(items[0]?.quantity ?? 0, 1); return <div className="space-y-4">{items.length === 0 ? <Empty text="No completed item sales in this period." /> : items.map((item, index) => <div key={`${item.name}-${item.category}`}><div className="flex items-start gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-white/5 text-xs text-slate-400">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><span className="truncate text-xs font-semibold text-slate-200">{item.name}</span><span className="shrink-0 text-[10px] text-slate-500">{money(item.revenue)}</span></div><p className="mt-0.5 text-[10px] text-slate-500">{item.quantity} sold · {item.category}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-linear-to-r from-emerald-500 to-cyan-400" style={{ width: `${Math.max(item.quantity / max * 100, 5)}%` }} /></div></div></div></div>)}</div>; }

const chartColors = ["#2f8cff", "#22c55e", "#a855f7", "#f59e0b", "#ef476f", "#06b6d4"];
function DonutChart({ data, total }: { data: Slice[]; total: number }) { const sum = data.reduce((value, item) => value + item.value, 0); let cursor = 0; const gradient = data.length ? data.map((item, index) => { const start = cursor; cursor += sum ? item.value / sum * 100 : 0; return `${chartColors[index % chartColors.length]} ${start}% ${cursor}%`; }).join(", ") : "#1e293b 0 100%"; return <div className="flex items-center gap-5"><div className="relative h-32 w-32 shrink-0 rounded-full" style={{ background: `conic-gradient(${gradient})` }}><div className="absolute inset-5 grid place-items-center rounded-full bg-[#0d1b2a] text-center"><div><p className="text-sm font-bold text-white">{compactMoney(total)}</p><p className="text-[9px] text-slate-500">Total sales</p></div></div></div><div className="min-w-0 flex-1 space-y-2">{data.length === 0 ? <Empty text="No sales data." /> : data.slice(0, 6).map((item, index) => <div key={item.label} className="flex items-center justify-between gap-2 text-[11px]"><span className="flex min-w-0 items-center gap-2 text-slate-400"><i className="h-2 w-2 shrink-0 rounded-full" style={{ background: chartColors[index % chartColors.length] }} /><span className="truncate capitalize">{item.label}</span></span><span className="font-semibold text-slate-200">{sum ? Math.round(item.value / sum * 100) : 0}%</span></div>)}</div></div>; }

function BarChart({ data }: { data: Trend[] }) { const max = Math.max(...data.map((item) => item.value), 1); return <div className="flex h-44 items-end gap-1.5 border-b border-l border-white/8 px-3 pt-4">{data.map((item, index) => <div key={item.label} className="flex h-full min-w-0 flex-1 flex-col justify-end gap-2"><div className="group relative mx-auto w-full max-w-7 rounded-t bg-linear-to-t from-emerald-600 to-emerald-300" style={{ height: `${Math.max(item.value / max * 100, item.value ? 8 : 1)}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 rounded bg-slate-700 px-1.5 py-0.5 text-[9px] group-hover:block">{item.value}</span></div>{index % 2 === 0 && <span className="truncate text-center text-[8px] text-slate-600">{item.label}</span>}</div>)}</div>; }

function LiveOrders({ orders }: { orders: DashboardData["liveOrders"] }) { return <div className="space-y-1">{orders.length === 0 ? <Empty text="Kitchen queue is clear." /> : orders.map((order) => <div key={order.id} className="relative border-l border-white/10 py-3 pl-5 before:absolute before:-left-1 before:top-5 before:h-2 before:w-2 before:rounded-full before:bg-sky-400"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="text-xs text-slate-500">#{order.id.split("-")[0].toUpperCase()}</span><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold ${statusColor[order.status]}`}>{order.status}</span></div><span className="text-[10px] text-slate-600">{new Date(order.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div><p className="mt-1 truncate text-xs text-slate-300">{order.itemSummary}</p><div className="mt-1 flex justify-between text-[10px] text-slate-500"><span>{typeLabel(order.orderType)}</span><span>{money(order.totalAmount)}</span></div></div>)}</div>; }
function InventoryList({ items }: { items: DashboardData["inventory"] }) { return <div className="space-y-2">{items.length === 0 ? <Empty text="No low-stock products." /> : items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-white/3 px-3 py-2.5"><div><p className="text-xs font-semibold text-slate-200">{item.name}</p><p className="text-[10px] text-slate-500">{item.category}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${item.stock === 0 ? "bg-rose-400/15 text-rose-300" : "bg-amber-400/15 text-amber-300"}`}>{item.stock === 0 ? "Sold out" : `${item.stock} left`}</span></div>)}</div>; }

function RecentOrders({ orders }: { orders: DashboardData["recentOrders"] }) {
  const [selected, setSelected] = useState<DashboardData["recentOrders"][number] | null>(null);
  return <><div className="overflow-x-auto"><table className="w-full min-w-175 text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-slate-600"><tr><th className="pb-3">Order</th><th className="pb-3">Type</th><th className="pb-3">Items</th><th className="pb-3">Payment</th><th className="pb-3">Total</th><th className="pb-3">Status</th><th className="pb-3 text-right">Time</th></tr></thead><tbody className="divide-y divide-white/5">{orders.map((order) => <tr key={order.id} className="cursor-pointer text-slate-400 hover:bg-white/2" onClick={() => setSelected(order)}><td className="py-3 font-semibold text-slate-200">#{order.id.split("-")[0].toUpperCase()}</td><td className="py-3">{typeLabel(order.orderType)}{order.tableNumber ? ` · ${order.tableNumber}` : ""}</td><td className="max-w-55 truncate py-3" title={order.itemSummary}>{order.itemCount} · {order.itemSummary}</td><td className="py-3 capitalize">{order.paymentMethod}</td><td className="py-3 font-semibold text-white">{money(order.totalAmount)}</td><td className="py-3"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${statusColor[order.status]}`}>{order.status}</span></td><td className="py-3 text-right">{new Date(order.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td></tr>)}</tbody></table>{orders.length === 0 && <Empty text="No orders yet." />}</div>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><div role="dialog" aria-modal="true" aria-label="Order details" className="w-full max-w-md rounded-2xl border border-white/10 bg-[#101e2e] p-5 shadow-2xl"><div className="flex justify-between gap-4"><div><h3 className="font-bold text-white">Order #{selected.id.split("-")[0].toUpperCase()}</h3><p className="mt-1 text-xs text-slate-500">{typeLabel(selected.orderType)} · {selected.paymentMethod}</p></div><button aria-label="Close order details" onClick={() => setSelected(null)} className="h-8 w-8 rounded-lg border border-white/10 text-slate-400">✕</button></div><p className="mt-5 text-sm leading-relaxed text-slate-300">{selected.itemSummary}</p><div className="mt-5 flex items-center justify-between border-t border-white/8 pt-4"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusColor[selected.status]}`}>{selected.status}</span><span className="text-lg font-bold text-white">{money(selected.totalAmount)}</span></div><Link href={`/receipt/${selected.id}`} target="_blank" className="mt-4 block rounded-xl bg-sky-500 px-4 py-3 text-center text-sm font-bold text-white">Open receipt</Link></div></div>}</>;
}

function BusinessHealth({ data }: { data: DashboardData }) { const rows = [["All-time revenue", money(data.allTime.revenue)], ["Completed orders", String(data.allTime.orders)], ["Active products", String(data.catalog.products)], ["Active categories", String(data.catalog.categories)], ["Available deals", String(data.catalog.availableDeals)]]; return <div className="space-y-3">{rows.map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-white/5 pb-3 last:border-0 last:pb-0"><span className="text-xs text-slate-500">{label}</span><span className="text-sm font-bold text-slate-200">{value}</span></div>)}</div>; }
function QuickActions() { return <div className="grid gap-2"><Link href="/terminal" className="rounded-xl bg-emerald-500 px-4 py-3 text-center text-sm font-bold text-white">+ New order</Link><Link href="/admin/menu" className="rounded-xl bg-blue-500 px-4 py-3 text-center text-sm font-bold text-white">Manage menu</Link><Link href="/admin/deals" className="rounded-xl bg-violet-500 px-4 py-3 text-center text-sm font-bold text-white">Manage deals</Link><Link href="/admin/coupons" className="rounded-xl bg-amber-500 px-4 py-3 text-center text-sm font-bold text-white">Manage coupons</Link><Link href="/kitchen" className="rounded-xl border border-white/10 px-4 py-3 text-center text-sm font-bold text-slate-300">Kitchen display</Link></div>; }
function Empty({ text }: { text: string }) { return <p className="py-8 text-center text-xs text-slate-600">{text}</p>; }
